# Preset: correlated alphas run

[evolution]
# Prioritize Sharpe, then IC; allow correlation (no corr penalty)
selection_metric = "fixed"

# Sharpe focus
sharpe_proxy_w = 1.8        # 1.5–2.0 typical

# IC stability (secondary)
ic_std_penalty_w = 0.05
ic_tstat_w = 0.3

# Turnover (mild)
turnover_penalty_w = 0.03

# Correlation pressure (disabled)
corr_penalty_w = 0.0        # disable correlation penalty entirely
corr_cutoff = 0.50
hof_corr_mode = "flat"

# Disable diversity boosts
novelty_boost_w = 0.0
novelty_struct_w = 0.0

# Optional: weight recent IC more
temporal_decay_half_life = 60

# Modest ramping; selection uses fixed fitness anyway
ramp_fraction = 0.25
ramp_min_gens = 4

