[evolution]
data_dir = "./data"
max_lookback_data_option = "common_1200"
min_common_points = 300
eval_lag = 1
# search behavior
selection_metric = "auto"
ramp_fraction = 0.5
ramp_min_gens = 5
novelty_boost_w = 0.04
corr_penalty_w = 0.25
hof_per_gen = 5
pop_size = 150
fresh_rate = 0.2
ops_split_jitter = 0.1
sector_neutralize = true
workers = 1
seed = 42
moea_enabled = true
moea_elite_frac = 0.25
mf_enabled = true
mf_initial_fraction = 0.4
mf_promote_fraction = 0.3
mf_min_promote = 12

[backtest]
data_dir = "./data"
max_lookback_data_option = "common_1200"
min_common_points = 300
eval_lag = 1
top_to_backtest = 5
fee = 1.0
hold = 1
scale = "rank"
long_short_n = 6
stop_loss_pct = 0.0
sector_neutralize_positions = false
ensemble_mode = true
ensemble_size = 5
ensemble_max_corr = 0.3
