[evolution]
bandit_enabled = false
corr_cutoff = 0.15
corr_penalty_w = 0.25
cv_embargo = 0
cv_k_folds = 0
data_dir = "./data"
early_abort_bars = 20
early_abort_t = 0.05
early_abort_xs = 0.05
elite_keep = 1
eval_cache_size = 128
eval_lag = 1
flat_bar_threshold = 0.25
fresh_rate = 0.2
generations = 5
hof_corr_mode = "flat"
hof_per_gen = 5
hof_size = 20
ic_phase_gens = 0
ic_std_penalty_w = 0.1
ic_tstat_w = 0
keep_dupes_in_hof = false
max_lookback_data_option = "common_1200"
max_matrix_operands = 4
max_ops = 87
max_predict_ops = 21
max_scalar_operands = 10
max_setup_ops = 21
max_update_ops = 45
max_vector_operands = 16
mf_enabled = true
mf_initial_fraction = 0.4
mf_min_promote = 12
mf_promote_fraction = 0.3
min_common_points = 300
moea_elite_frac = 0.25
moea_enabled = true
novelty_boost_w = 0.04
novelty_struct_w = 0
ops_split_jitter = 0.1
p_cross = 0
p_mut = 0.9
parsimony_jitter_pct = 0
parsimony_penalty = 0.002
pop_size = 150
quiet = false
ramp_fraction = 0.5
ramp_min_gens = 5
rank_softmax_beta_floor = 0
rank_softmax_beta_target = 2
scale = "zscore"
sector_mapping = "[object Object]"
sector_neutralize = true
seed = 42
selection_metric = "auto"
sharpe_proxy_w = 0
split_weighting = "equal"
t_flat_guard = 0.05
temporal_decay_half_life = 0
tournament_k = 10
train_points = 840
turnover_penalty_w = 0.05
use_train_val_splits = true
val_points = 360
winsor_p = 0.02
workers = 1
xs_flat_guard = 0.05

[backtest]
annualization_factor = 2190
dd_limit = 0
dd_reduction = 0.5
ensemble_max_corr = 0.3
ensemble_mode = true
ensemble_size = 5
ensemble_weighting = "equal"
fee = 1
hold = 1
long_short_n = 6
max_leverage = 2
max_lookback_data_option = "common_1200"
min_leverage = 0.25
scale = "zscore"
sector_neutralize_positions = false
stop_loss_pct = 3
top_to_backtest = 5
volatility_lookback = 30
volatility_target = 0
